name: heroku

services:
  node:
    # --- node service ---
    type: 'node:18'
    scanner: false
    # --- Build steps ---
    build:
      - echo "Build steps..."
      # Install Heroku CLI
      - npm install -g heroku
      - echo "Build steps done."

tooling:
  heroku:
    service: node
    description: "Run heroku CLI commands"
  node:
    service: node
    description: "Run node commands"
  yarn:
    service: node
    description: "Run yarn commands"
  npm:
    service: node
    description: "Run npm commands"
  heroku:login:
    service: node
    description: "Interactive login to Heroku"
    cmd:
      - heroku login -i
  heroku:push:
    service: node
    description: "Push branch 'main' to Heroku"
    cmd:
      - git push heroku main
