name: heroku

services:
  appserver:
    # --- node service ---
    type: 'node:18'
    scanner: false
    # --- Build steps ---
    build_as_root:
      - echo "Build as root steps ..."
      - apt update
      - apt install -y cmake
      - echo "Build as root steps done."
    build:
      - echo "Build steps ..."
      # Install Heroku CLI
      - echo "Installing packages ..."
      - yarn global add heroku
      - echo "Build steps done."

tooling:
  heroku:
    service: appserver
    description: "Run heroku CLI commands"
  node:
    service: appserver
    description: "Run node commands"
  yarn:
    service: appserver
    description: "Run yarn commands"
  npm:
    service: appserver
    cmd: echo && echo "Please Use yarn rather than npm."
